# Generated by Django 3.2.15 on 2022-12-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelartentry',
            name='art',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
