# Generated by Django 3.2.15 on 2022-12-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepix', '0002_alter_pixelartentry_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelartentry',
            name='art',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
