# Generated by Django 3.2.15 on 2022-12-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepix', '0003_alter_pixelartentry_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelartentry',
            name='art',
            field=models.FileField(upload_to=''),
        ),
    ]
